on:
  push:
    branches:
      - '**'
      - '!src'

jobs:
  nikola_build:
    runs-on: ubuntu-latest
    name: 'Build Nikola'
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Build Nikola
      uses: getnikola/nikola-action@v3
      with:
        dry_run: true
